export const Keys = {
  posts: "posts",
  post: (id: string) => `post:${id}`,
  comments: (postId: string) => `comments:${postId}`,
  spaces: "spaces",
  space: (id: string) => `space:${id}`,
  members: (spaceId: string) => `members:${spaceId}`,
  bans: (spaceId: string) => `bans:${spaceId}`,
  mutes: (spaceId: string) => `mutes:${spaceId}`,
  invitations: (spaceId: string) => `invitations:${spaceId}`,
  rules: (spaceId: string) => `rules:${spaceId}`,
  postFlairs: (spaceId: string) => `postFlairs:${spaceId}`,
  userFlair: (spaceId: string, userId: string) => `userFlair:${spaceId}:${userId}`,
  reports: (spaceId: string) => `reports:${spaceId}`,
  moderationLogs: (spaceId: string) => `moderationLogs:${spaceId}`,
  wiki: (spaceId: string) => `wiki:${spaceId}`,
  wikiPage: (pageId: string) => `wikiPage:${pageId}`,
  poll: (postId: string) => `poll:${postId}`,
  user: (id: string) => `user:${id}`,
  me: "me",
  saved: "saved",
  hidden: "hidden",
  notifications: "notifications",
  messages: "messages",
  works: "works",
  work: (id: string) => `work:${id}`,
  workCredits: (id: string) => `work:${id}:credits`,
  workTags: (id: string) => `work:${id}:tags`,
  workAliases: (id: string) => `work:${id}:aliases`,
  workRating: (id: string) => `work:${id}:rating`,
  workRevisions: (id: string) => `work:${id}:revisions`,
  workChapters: (id: string) => `work:${id}:chapters`,
  workVariants: (id: string) => `work:${id}:variants`,
  workRequirements: (id: string) => `work:${id}:requirements`,
  workExternalRefs: (id: string) => `work:${id}:externalRefs`,
  chapter: (id: string) => `chapter:${id}`,
  creators: "creators",
  creator: (id: string) => `creator:${id}`,
  creatorWorks: (id: string) => `creator:${id}:works`,
  creatorRevisions: (id: string) => `creator:${id}:revisions`,
  library: "library",
  libraryOf: (userId: string) => `library:${userId}`,
  shelves: "shelves",
  shelf: (id: string) => `shelf:${id}`,
  shelfItems: (id: string) => `shelf:${id}:items`,
} as const;
