apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base
  - ../../infra

patches:
  - target:
      kind: Ingress
      name: openworks
    patch: |
      - op: replace
        path: /spec/rules/0/host
        value: openworks.dev.local

  - target:
      kind: Deployment
      name: backend
    patch: |
      - op: replace
        path: /spec/template/spec/containers/0/resources/requests/cpu
        value: 50m
      - op: replace
        path: /spec/template/spec/containers/0/resources/requests/memory
        value: 128Mi
      - op: replace
        path: /spec/template/spec/containers/0/resources/limits/memory
        value: 256Mi

  - target:
      kind: Deployment
      name: frontend
    patch: |
      - op: replace
        path: /spec/template/spec/containers/0/resources/requests/cpu
        value: 50m
      - op: replace
        path: /spec/template/spec/containers/0/resources/requests/memory
        value: 128Mi
      - op: replace
        path: /spec/template/spec/containers/0/resources/limits/memory
        value: 256Mi
